services:
  - type: web
    name: newflixweb
    env: node
    plan: free
    buildCommand: 'npm install'
    startCommand: 'node server.js'
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        value: mongodb+srv://flixapp:Muhammed5858@flixapp.aexhj.mongodb.net/?retryWrites=true&w=majority&appName=flixapp
- key: SESSION_SECRET
        value: test_scetre_2024


